namespace: elk

elk_version: 8.15.0

security:
  enabled: false      # Enable security
  ssl_enabled: false  # Enable https

elasticsearch:
  java_opts: '-Xms1g -Xmx1g'    # Define memory for elastisearch jvm
  storage:
    data_path: /opt/mip-deployment/.stored_data/elasticsearch
    data_size: 10Gi

logstash:
  expose_monitoring_port: false   # Expose only for monitoring logstash performance
  k8s_logs_consumer_port: 30510
  docker_logs_consumer_port: 30520
