apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
spec:
  version: {{ .Values.version }}
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 20Gi  # Adjust based on your needs
            storageClassName: {{ .Values.storageClass | default "microk8s-hostpath" }}
        
  # Authentication with Keycloak requires a paid license
  # secureSettings:
  #   - secretName: oidc-client-secret
  # config:
  #   xpack.security.authc.realms.oidc.oidc1:
  #     order: 2
  #     rp.client_id: "datacatalogue"
  #     rp.response_type: "code"
  #     rp.redirect_uri: "https://192.168.38.128:5601/api/security/oidc/callback"
  #     rp.post_logout_redirect_uri: "https://kibana.example.com/logged_out"
  #     rp.client_secret: "aQG4C7Ao22ll6zGfdut3uLVvHJdVl9et"    # change to use secret
  #     op.issuer: "https://iam.ebrains.eu/auth/realms/MIP"
  #     op.authorization_endpoint: "https://iam.ebrains.eu/auth/realms/MIP/protocol/openid-connect/auth"
  #     op.token_endpoint: "https://iam.ebrains.eu/auth/realms/MIP/protocol/openid-connect/token"
  #     op.userinfo_endpoint: "https://iam.ebrains.eu/auth/realms/MIP/protocol/openid-connect/userinfo"
  #     op.jwkset_path: "https://iam.ebrains.eu/auth/realms/MIP/protocol/openid-connect/certs"
  #     claims.principal: "email"
  #     claims.mail: "email"
  #     claims.name: "name"
  #     claims.groups: "mip_eck"

--- 


---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 31001
