{{- if .Values.logstash.enabled }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline-config
  namespace: {{ .Values.namespace }}
data:
  logstash.conf: |
{{ .Files.Get "files/logstash/pipeline/logstash.conf" | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: {{ .Values.namespace }}
data:
  logstash.yml: |
{{ .Files.Get "files/logstash/config/logstash.yml" | indent 4 }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:{{ .Values.elk_version }}
        ports:
        - containerPort: 5044
        - containerPort: 5010     # Consume k8s logs (TCP)
        - containerPort: 5020     # Consume docker logs (TCP)
        {{- if .Values.logstash.expose_monitoring_port }}
        - containerPort: 9600
        {{- end }}
        env:
        - name: xpack.security.enabled
          value: "{{ .Values.logstash.security.enabled }}"
        volumeMounts:
        - name: logstash-pipeline-config
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          subPath: logstash.conf
          readOnly: true
        - name: logstash-config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          readOnly: true
      volumes:
      - name: logstash-pipeline-config
        configMap:
          name: logstash-pipeline-config
      - name: logstash-config
        configMap:
          name: logstash-config

---

apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: logstash
  ports:
  - name: logstash
    port: 5044
    targetPort: 5044
  - name: logstash-monitoring
    port: 9600
    targetPort: 9600

---

apiVersion: v1
kind: Service
metadata:
  name: logstash-log-consumer
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: logstash
  ports:
  - name: k8s-logs-consumer
    protocol: TCP
    port: 5010
    targetPort: 5010
    nodePort: {{ .Values.logstash.k8s_logs_consumer_port }}
  - name: docker-logs-consumer
    protocol: TCP
    port: 5020
    targetPort: 5020
    nodePort: {{ .Values.logstash.docker_logs_consumer_port }}

{{- end }}
