apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: k8s-local-storage
  namespace: {{ .Values.namespace }}
  labels:
    app: k8s-local-storage
provisioner: k8s.io/microk8s-hostpath
#volumeBindingMode: WaitForFirstConsumer
volumeBindingMode: Immediate
