version: '3.7'

services:
  portalbackend_db:
    image: postgres:11.3-alpine
    volumes:
      - ./.stored_data/portalbackenddb:/var/lib/postgresql/data
    hostname: portalbackend_db
    environment:
      POSTGRES_PASSWORD: test
    command: -p 5433
    expose:
      - 5433
    restart: unless-stopped

  create_dbs:
    image: hbpmip/create-databases:1.1.0
    depends_on:
      - portalbackend_db
    environment:
      DB_HOST: portalbackend_db
      DB_PORT: 5433
      DB_ADMIN_USER: postgres
      DB_ADMIN_PASSWORD: test
      DB4: portal
      USER4: portal
      PASSWORD4: portalpwd
    restart: on-failure

  portalbackend:
    image: hbpmip/portal-backend:${PORTALBACKEND}
    ports:
      - '8080:8080'
      - '8089:8089'
    environment:
      ### API ###
      LOG_LEVEL: INFO
      LOG_LEVEL_FRAMEWORK: INFO
      AUTHENTICATION: ${KEYCLOAK_AUTHENTICATION}
      ### Database ###
      PORTAL_DB_URL: jdbc:postgresql://portalbackend_db:5433/portal
      PORTAL_DB_SERVER: portalbackend_db:5433
      PORTAL_DB_USER: portal
      PORTAL_DB_PASSWORD: portalpwd
      ### Exareme2 ###
      EXAREME2_URL: ${EXAREME2_URL}
      ### Exareme ###
      EXAREME_URL: http://${EXAREME_IP}:9090
      ### Keycloak ###
      KEYCLOAK_AUTH_URL: ${KEYCLOAK_PROTOCOL}://${KEYCLOAK_URL}/auth/
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_SSL_REQUIRED: ${KEYCLOAK_SSL_REQUIRED}
    depends_on:
      - create_dbs
    volumes:
      - ./config:/opt/portal/api
      - ./logs:/opt/portal/logs
    restart: unless-stopped

  gateway:
    image: hbpmip/gateway:${GATEWAY}
    environment:
      ENGINE_TYPE: exareme
      ENGINE_BASE_URL: http://portalbackend:8080/services/
      GATEWAY_PORT: 8081
    ports:
      - '8081:8081'
    depends_on:
      - portalbackend
    restart: unless-stopped

  frontend:
    image: hbpmip/portal-frontend:${FRONTEND}
    depends_on:
      - gateway
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./.stored_data/caddy/caddy_data:/data
    environment:
      ERROR_LOG_LEVEL: info
      PORTAL_BACKEND_SERVER: portalbackend:8080
      PORTAL_BACKEND_CONTEXT: services
      GATEWAY_SERVER: gateway:8081
      INSTANCE_NAME: 'MIP ${MIP}'
      VERSION: 'Frontend: ${FRONTEND}, Gateway: ${GATEWAY}, Backend: ${PORTALBACKEND}, Exareme: ${EXAREME}'
      TRACKER_ID: UA-80660232-5
      DATACATALOGUE_SERVER: ${DATACATALOGUE_PROTOCOL}://${DATACATALOGUE_HOST}
      PUBLIC_MIP_HOST: ${PUBLIC_MIP_HOST}
      PUBLIC_MIP_PROTOCOL: ${PUBLIC_MIP_PROTOCOL}
    restart: unless-stopped
