version: '3.2'

networks:
  frontend:
  backend:

services:
  galaxy:
    image: hbpmip/galaxy:${GALAXY}
    environment:
      - EXAREME_IP=${EXAREME_IP}
      - EXAREME_PORT=9090
      - PASSWORD=password
    command: bash -c "htpasswd -bc /etc/apache2/htpasswd admin $$PASSWORD && ./createExaremeVariables.sh && /etc/init.d/apache2 restart && ./run.sh"
    expose:
      - '80'
    ports:
      - '8090:80'
    networks:
      - backend

  portalbackend_db:
    image: postgres:11.3-alpine
    hostname: portalbackend_db
    environment:
      POSTGRES_PASSWORD: test
    networks:
      - backend

  create_dbs:
    image: hbpmip/create-databases:1.1.0
    environment:
      DB_HOST: portalbackend_db
      DB_PORT: 5432
      DB_ADMIN_USER: postgres
      DB_ADMIN_PASSWORD: test
      DB4: portal
      USER4: portal
      PASSWORD4: portalpwd
    depends_on:
      - portalbackend_db
    restart: on-failure
    networks:
      - backend

  portalbackend:
    image: hbpmip/portal-backend:${PORTALBACKEND}
    ports:
      - '8080:8080'
      - '8089:8089'
    environment:
      PORTAL_DB_URL: jdbc:postgresql://portalbackend_db:5432/portal
      PORTAL_DB_SERVER: portalbackend_db:5432
      PORTAL_DB_USER: portal
      PORTAL_DB_PASSWORD: portalpwd
      CONTEXT_PATH: /services
      AUTHENTICATION: 1
      FRONTEND_LOGIN_URL: http://${PUBLIC_MIP_IP}/services/login/hbp
      FRONTEND_AFTER_LOGIN_URL: http://${PUBLIC_MIP_IP}/
      FRONTEND_AFTER_LOGOUT_URL: http://${PUBLIC_MIP_IP}/services/login/hbp
      LOGGING_LEVEL_WEB: INFO
      LOGGING_LEVEL_HIBERNATE: INFO
      SESSION_TIMEOUT: 2592000
      RELEASE_STAGE: 'production'
      DATACENTER_LOCATION: 'CHUV'
      CONTAINER_ORCHESTRATION: 'docker-compose'

      EXAREME_URL: http://${EXAREME_IP}:9090

      GALAXY_URL: http://galaxy
      GALAXY_CONTEXT: nativeGalaxy/workflows/list
      GALAXY_API_KEY: d14a4cc5eebf805eb2ff261374ed08a2
      GALAXY_USERNAME: admin
      GALAXY_PASSWORD: password
      CLIENT_ID: vanilla
      CLIENT_SECRET: SaNJbC2YFHPhPM-tGiJ1b7tmAA
      AUTH_URI: "https://iam.humanbrainproject.eu/auth/realms/MIPTEST/protocol/openid-connect/auth"
      USER_INFO_URI: "https://iam.humanbrainproject.eu/auth/realms/MIPTEST/protocol/openid-connect/userinfo"
      TOKEN_URI: "https://iam.humanbrainproject.eu/auth/realms/MIPTEST/protocol/openid-connect/token"
      LOGOUT_URI: "https://iam.humanbrainproject.eu/auth/realms/MIPTEST/protocol/openid-connect/logout"
    depends_on:
      - create_dbs
    restart: on-failure
    volumes:
      - ./config:/opt/portal/api
      - ./logs:/opt/portal/logs
    networks:
      - backend
      - frontend

  frontend:
    image: hbpmip/portal-frontend:${FRONTEND}
    depends_on:
      - portalbackend
    ports:
      - '80:80'
    environment:
      WORKER_PROCESSES: 1
      ERROR_LOG_LEVEL: warn
      PORTAL_VIRTUAL_HOST: frontend
      PORTAL_BACKEND_SERVER: portalbackend:8080
      PORTAL_BACKEND_CONTEXT: services
      INSTANCE_NAME: 'MIP ${MIP}'
      VERSION: 'Frontend: ${FRONTEND}, Backend: ${PORTALBACKEND}, Exareme: ${EXAREME}, Galaxy: ${GALAXY}'
      TRACKER_ID: UA-80660232-5
      GALAXY_URL: http://galaxy/nativeGalaxy
      KEYCLOAK_AUTH_URL: "https://iam.humanbrainproject.eu/auth/"
      KEYCLOAK_LOGIN_URL: "https://iam.humanbrainproject.eu/auth/realms/MIP/protocol/openid-connect/auth"
    restart: on-failure
    networks:
      - frontend
      - backend
