version: '3.2'

services:
  galaxy:
    image: hbpmip/galaxy:${GALAXY}
    expose:
      - '80'
    ports:
      - '8090:80'
    environment:
      - EXAREME_IP=${EXAREME_IP}
      - EXAREME_PORT=9090
      - PASSWORD=password
    command: bash -c "htpasswd -bc /etc/apache2/htpasswd admin $$PASSWORD && ./createExaremeVariables.sh && /etc/init.d/apache2 restart && ./run.sh"
    restart: unless-stopped

  portalbackend_db:
    image: postgres:11.3-alpine
    volumes:
      - ./.stored_data/portalbackenddb:/var/lib/postgresql/data
    hostname: portalbackend_db
    environment:
      POSTGRES_PASSWORD: test
    command: -p 5433
    expose:
      - 5433
    restart: unless-stopped

  create_dbs:
    image: hbpmip/create-databases:1.1.0
    depends_on:
      - portalbackend_db
    environment:
      DB_HOST: portalbackend_db
      DB_PORT: 5433
      DB_ADMIN_USER: postgres
      DB_ADMIN_PASSWORD: test
      DB4: portal
      USER4: portal
      PASSWORD4: portalpwd
    restart: on-failure

  portalbackend:
    image: hbpmip/portal-backend:${PORTALBACKEND}
    ports:
      - '8080:8080'
      - '8089:8089'
    environment:
      ### API ###
      LOG_LEVEL: INFO
      LOG_LEVEL_FRAMEWORK: INFO
      AUTHENTICATION: ${KEYCLOAK_AUTHENTICATION}
      ### Database ###
      PORTAL_DB_URL: jdbc:postgresql://portalbackend_db:5433/portal
      PORTAL_DB_SERVER: portalbackend_db:5433
      PORTAL_DB_USER: portal
      PORTAL_DB_PASSWORD: portalpwd
      ### Exareme ###
      EXAREME_URL: http://exareme_master:9090
      ### Galaxy ###
      GALAXY_URL: http://galaxy
      GALAXY_API_KEY: d14a4cc5eebf805eb2ff261374ed08a2
      GALAXY_USERNAME: admin
      GALAXY_PASSWORD: password
      ### Keycloak ###
      KEYCLOAK_AUTH_URL: ${KEYCLOAK_PROTOCOL}://${KEYCLOAK_URL}/auth/
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
    depends_on:
      - create_dbs
    volumes:
      - ./config:/opt/portal/api
      - ./logs:/opt/portal/logs
    restart: unless-stopped

  frontend:
    image: hbpmip/portal-frontend:${FRONTEND}
    depends_on:
      - portalbackend
    ports:
      - '80:80'
    environment:
      WORKER_PROCESSES: 1
      ERROR_LOG_LEVEL: warn
      PORTAL_VIRTUAL_HOST: frontend
      PORTAL_BACKEND_SERVER: portalbackend:8080
      PORTAL_BACKEND_CONTEXT: services
      INSTANCE_NAME: 'MIP ${MIP}'
      VERSION: 'Frontend: ${FRONTEND}, Backend: ${PORTALBACKEND}, Exareme: ${EXAREME}, Galaxy: ${GALAXY}'
      TRACKER_ID: UA-80660232-5
      GALAXY_URL: http://galaxy/nativeGalaxy
      DATACATALOGUE_SERVER: ${DATACATALOGUE_PROTOCOL}://${DATACATALOGUE_HOST}
    restart: unless-stopped
