version: '3.2'

services:
  galaxy:
    image: hbpmip/galaxy:${GALAXY}
    environment:
      - EXAREME_IP=${EXAREME_IP}
      - EXAREME_PORT=9090
      - PASSWORD=password
    command: bash -c "htpasswd -bc /etc/apache2/htpasswd admin $$PASSWORD && ./createExaremeVariables.sh && /etc/init.d/apache2 restart && ./run.sh"
    expose:
      - '80'
    ports:
      - '8090:80'

  portalbackend_db:
    image: postgres:11.3-alpine
    volumes:
      - ./.stored_data/portalbackenddb:/var/lib/postgresql/data
    hostname: portalbackend_db
    environment:
      POSTGRES_PASSWORD: test

  create_dbs:
    image: hbpmip/create-databases:1.1.0
    environment:
      DB_HOST: portalbackend_db
      DB_PORT: 5432
      DB_ADMIN_USER: postgres
      DB_ADMIN_PASSWORD: test
      DB4: portal
      USER4: portal
      PASSWORD4: portalpwd
    depends_on:
      - portalbackend_db
    restart: on-failure

  portalbackend:
    image: hbpmip/portal-backend:${PORTALBACKEND}
    ports:
      - '8080:8080'
      - '8089:8089'
    environment:
      PORTAL_DB_URL: jdbc:postgresql://portalbackend_db:5432/portal
      PORTAL_DB_SERVER: portalbackend_db:5432
      PORTAL_DB_USER: portal
      PORTAL_DB_PASSWORD: portalpwd
      CONTEXT_PATH: /services
      AUTHENTICATION: ${KEYCLOAK_AUTHENTICATION}
      FRONTEND_LOGIN_URL: http://${PUBLIC_MIP_HOST}/services/login/hbp
      FRONTEND_AFTER_LOGIN_URL: http://${PUBLIC_MIP_HOST}/
      FRONTEND_AFTER_LOGOUT_URL: http://${PUBLIC_MIP_HOST}/services/login/hbp
      LOGGING_LEVEL_WEB: INFO
      LOGGING_LEVEL_HIBERNATE: INFO
      SESSION_TIMEOUT: 2592000
      RELEASE_STAGE: 'production'
      DATACENTER_LOCATION: 'CHUV'
      CONTAINER_ORCHESTRATION: 'docker-compose'
      EXAREME_URL: http://${EXAREME_IP}:9090
      GALAXY_URL: http://galaxy
      GALAXY_CONTEXT: nativeGalaxy/workflows/list
      GALAXY_API_KEY: d14a4cc5eebf805eb2ff261374ed08a2
      GALAXY_USERNAME: admin
      GALAXY_PASSWORD: password
      CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      AUTH_URI: ${KEYCLOAK_PROTOCOL}://${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth
      USER_INFO_URI: ${KEYCLOAK_PROTOCOL}://${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/userinfo
      TOKEN_URI: ${KEYCLOAK_PROTOCOL}://${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
      LOGOUT_URI: ${KEYCLOAK_PROTOCOL}://${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/logout
    depends_on:
      - create_dbs
    restart: on-failure
    volumes:
      - ./config:/opt/portal/api
      - ./logs:/opt/portal/logs

  frontend:
    image: hbpmip/portal-frontend:${FRONTEND}
    depends_on:
      - portalbackend
      - datacataloguefrontend
    ports:
      - '80:80'
    links:
      - datacataloguefrontend
    environment:
      WORKER_PROCESSES: 1
      ERROR_LOG_LEVEL: warn
      PORTAL_VIRTUAL_HOST: frontend
      PORTAL_BACKEND_SERVER: portalbackend:8080
      PORTAL_BACKEND_CONTEXT: services
      INSTANCE_NAME: 'MIP ${MIP}'
      VERSION: 'Frontend: ${FRONTEND}, Backend: ${PORTALBACKEND}, Exareme: ${EXAREME}, Galaxy: ${GALAXY}'
      TRACKER_ID: UA-80660232-5
      GALAXY_URL: http://galaxy/nativeGalaxy
      DATACATALOGUE_SERVER: datacataloguefrontend:4200
      KEYCLOAK_AUTH_URL: ${KEYCLOAK_PROTOCOL}://${KEYCLOAK_URL}/auth/
      KEYCLOAK_LOGIN_URL: ${KEYCLOAK_PROTOCOL}://${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth
    restart: on-failure

  datacatalogue_backend:
    image: hbpmip/datacatalogue_spring_boot_backend:latest
    ports:
      - 8086
    depends_on:
      - datacatalogue_postgres
    links:
      - datacatalogue_postgres
    environment:
      - spring.datasource.url=jdbc:postgresql://datacatalogue_postgres:5432/datacatalog
      - spring.datasource.username=andy
      - spring.datasource.password=password
      - keycloak.client.clientId=${KEYCLOAK_CLIENT_ID}
      - keycloak.client.clientSecret=${KEYCLOAK_CLIENT_SECRET}
      - keycloak.client.accessTokenUri=${KEYCLOAK_PROTOCOL}://${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
      - keycloak.resource.userInfoUri=${KEYCLOAK_PROTOCOL}://${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/userinfo
      - keycloak.client.userAuthorizationUri=${KEYCLOAK_PROTOCOL}://${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth
      - keycloak.client.redirect_uri=http://localhost:4200/pathologies


  datacataloguefrontend:
    image: hbpmip/datacatalogue_angular_frontend:latest
    ports:
      - 4200:4200
    depends_on:
      - datacatalogue_backend
    links:
      - datacatalogue_backend
    restart: on-failure

  datacatalogue_postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=datacatalog
      - POSTGRES_USER=andy
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: on-failure
