EXTERNAL_IP: 192.168.38.128

engines:
  exareme2:
    URL: http://192.168.38.128:30000

mip:
  LINK: direct
  EXTERNAL_PROTOCOL: http
  PUBLIC_PROTOCOL: http
  PUBLIC_HOST: 192.168.38.128

datacatalogue:
  PROTOCOL: https
  HOST: datacatalogue.mip.ebrains.eu

keycloak:
  AUTHENTICATION: 0
  INTERNAL_AUTH: 0
  PROTOCOL: http
  URL: 192.168.38.128
  REALM: MIP
  CLIENT_ID: MIP
  CLIENT_SECRET: dae83a6b-c769-4186-8383-f0984c6edf05
  SSL_REQUIRED: none
