name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  portal-backend-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Deploy portalbackend and exareme2
        working-directory: ./tests/
        run: bash start.sh

      - name: Get deployment status
        run: docker ps

      - name: Run the tests
        working-directory: ./tests/
        run: bash test.sh
