name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  portal-backend-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Deploy portalbackend and exareme2
        working-directory: ./dev/
        run: bash start.sh

      - name: Get deployment status
        run: docker ps

      - name: Run the dev tests
        working-directory: ./dev/
        run: pytest -k "not test_federation_info.py"

      - name: Run the federation info tests
        working-directory: ./dev/
        run: pytest tests/test_federation_info.py
