name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  portal-backend-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install docker compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.30.1'

      - name: Docker compose version
        run: docker compose version

      - name: Deploy portalbackend and exareme2
        working-directory: ./dev/
        run: bash start.sh

      - name: Get deployment status
        run: docker ps

      - name: Install python dependencies
        working-directory: ./dev/
        run: pip install -r requirements.txt

      - name: Run the dev tests
        working-directory: ./dev/
        run: pytest
