name: CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]



jobs:

  portal-backend-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.5
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: ./tests/portal_backend_integration_tests/setup/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('./tests/portal_backend_integration_tests/setup/pyproject.toml') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        working-directory: ./tests/portal_backend_integration_tests/setup/
        run: poetry install --no-interaction

      - name: Configure the deployment env file
        run: cat .versions_env >> tests/portal_backend_integration_tests/setup/.env

      - name: Deploy portalbackend, exareme and mip-engine
        working-directory: ./tests/portal_backend_integration_tests/setup/
        run: docker-compose --env-file .env up -d

      - name: Initialize MONETDBs with mipdb initial metadata tables
        working-directory: ./tests/portal_backend_integration_tests/setup/
        run: |
          poetry run mipdb init --ip 127.0.0.1 --port 50001
          poetry run mipdb init --ip 127.0.0.1 --port 50002

      - name: Load data into MONETDB containers
        working-directory: ./tests/portal_backend_integration_tests/setup/
        run: |
          poetry run mipdb add-data-model test_data/dementia_v_0_1/CDEsMetadata.json --port 50001
          poetry run mipdb add-data-model test_data/dementia_v_0_1/CDEsMetadata.json --port 50002
          poetry run mipdb add-dataset test_data/dementia_v_0_1/edsd0.csv -d dementia -v 0.1 --port 50001
          poetry run mipdb add-dataset test_data/dementia_v_0_1/edsd1.csv -d dementia -v 0.1 --port 50001
          poetry run mipdb add-dataset test_data/dementia_v_0_1/edsd2.csv -d dementia -v 0.1 --port 50001
          poetry run mipdb add-dataset test_data/dementia_v_0_1/edsd3.csv -d dementia -v 0.1 --port 50001
          poetry run mipdb add-dataset test_data/dementia_v_0_1/edsd4.csv -d dementia -v 0.1 --port 50001
          poetry run mipdb add-dataset test_data/dementia_v_0_1/edsd5.csv -d dementia -v 0.1 --port 50002
          poetry run mipdb add-dataset test_data/dementia_v_0_1/edsd6.csv -d dementia -v 0.1 --port 50002
          poetry run mipdb add-dataset test_data/dementia_v_0_1/edsd7.csv -d dementia -v 0.1 --port 50002
          poetry run mipdb add-dataset test_data/dementia_v_0_1/edsd8.csv -d dementia -v 0.1 --port 50002
          poetry run mipdb add-dataset test_data/dementia_v_0_1/edsd9.csv -d dementia -v 0.1 --port 50002
          poetry run mipdb add-dataset test_data/dementia_v_0_1/ppmi0.csv -d dementia -v 0.1 --port 50001
          poetry run mipdb add-dataset test_data/dementia_v_0_1/ppmi1.csv -d dementia -v 0.1 --port 50001
          poetry run mipdb add-dataset test_data/dementia_v_0_1/ppmi2.csv -d dementia -v 0.1 --port 50001
          poetry run mipdb add-dataset test_data/dementia_v_0_1/ppmi3.csv -d dementia -v 0.1 --port 50001
          poetry run mipdb add-dataset test_data/dementia_v_0_1/ppmi4.csv -d dementia -v 0.1 --port 50001
          poetry run mipdb add-dataset test_data/dementia_v_0_1/ppmi5.csv -d dementia -v 0.1 --port 50002
          poetry run mipdb add-dataset test_data/dementia_v_0_1/ppmi6.csv -d dementia -v 0.1 --port 50002
          poetry run mipdb add-dataset test_data/dementia_v_0_1/ppmi7.csv -d dementia -v 0.1 --port 50002
          poetry run mipdb add-dataset test_data/dementia_v_0_1/ppmi8.csv -d dementia -v 0.1 --port 50002
          poetry run mipdb add-dataset test_data/dementia_v_0_1/ppmi9.csv -d dementia -v 0.1 --port 50002
          poetry run mipdb add-dataset test_data/dementia_v_0_1/desd-synthdata0.csv -d dementia -v 0.1 --port 50001
          poetry run mipdb add-dataset test_data/dementia_v_0_1/desd-synthdata1.csv -d dementia -v 0.1 --port 50001
          poetry run mipdb add-dataset test_data/dementia_v_0_1/desd-synthdata2.csv -d dementia -v 0.1 --port 50001
          poetry run mipdb add-dataset test_data/dementia_v_0_1/desd-synthdata3.csv -d dementia -v 0.1 --port 50001
          poetry run mipdb add-dataset test_data/dementia_v_0_1/desd-synthdata4.csv -d dementia -v 0.1 --port 50001
          poetry run mipdb add-dataset test_data/dementia_v_0_1/desd-synthdata5.csv -d dementia -v 0.1 --port 50002
          poetry run mipdb add-dataset test_data/dementia_v_0_1/desd-synthdata6.csv -d dementia -v 0.1 --port 50002
          poetry run mipdb add-dataset test_data/dementia_v_0_1/desd-synthdata7.csv -d dementia -v 0.1 --port 50002
          poetry run mipdb add-dataset test_data/dementia_v_0_1/desd-synthdata8.csv -d dementia -v 0.1 --port 50002
          poetry run mipdb add-dataset test_data/dementia_v_0_1/desd-synthdata9.csv -d dementia -v 0.1 --port 50002
          poetry run mipdb add-data-model test_data/tbi_v_0_1/CDEsMetadata.json --port 50001
          poetry run mipdb add-data-model test_data/tbi_v_0_1/CDEsMetadata.json --port 50002
          poetry run mipdb add-dataset test_data/tbi_v_0_1/dummy_tbi0.csv -d tbi -v 0.1 --port 50001
          poetry run mipdb add-dataset test_data/tbi_v_0_1/dummy_tbi1.csv -d tbi -v 0.1 --port 50001
          poetry run mipdb add-dataset test_data/tbi_v_0_1/dummy_tbi2.csv -d tbi -v 0.1 --port 50001
          poetry run mipdb add-dataset test_data/tbi_v_0_1/dummy_tbi3.csv -d tbi -v 0.1 --port 50001
          poetry run mipdb add-dataset test_data/tbi_v_0_1/dummy_tbi4.csv -d tbi -v 0.1 --port 50001
          poetry run mipdb add-dataset test_data/tbi_v_0_1/dummy_tbi5.csv -d tbi -v 0.1 --port 50002
          poetry run mipdb add-dataset test_data/tbi_v_0_1/dummy_tbi6.csv -d tbi -v 0.1 --port 50002
          poetry run mipdb add-dataset test_data/tbi_v_0_1/dummy_tbi7.csv -d tbi -v 0.1 --port 50002
          poetry run mipdb add-dataset test_data/tbi_v_0_1/dummy_tbi8.csv -d tbi -v 0.1 --port 50002
          poetry run mipdb add-dataset test_data/tbi_v_0_1/dummy_tbi9.csv -d tbi -v 0.1 --port 50002

      - name: Wait for services to be up
        uses: jakejarvis/wait-action@master
        with:
          time: '120s'

      - name: Get deployment status
        run: docker ps

      - name: Run the success tests
        working-directory: ./tests/portal_backend_integration_tests/setup/
        run: poetry run pytest ../success

      - name: Run the failure tests
        working-directory: ./tests/portal_backend_integration_tests/setup/
        run: poetry run pytest ../fail

